### ISSUE TITLE
`?` or `#` query start not working (either documentation, JsBin or the source code is not correct)

### ISSUE THREAD

**Issue by cduivis** [canjs/can-deparam#17]
The Documentation : https://canjs.com/doc/can-deparam.html states that deparam should be able to handle queries starting with `?` or `#`.
When testing this with the JsBin provided on the page it becomes clear that it doesn't (at least not the code run by JsBin.
The unit tests written also don't check for this behavior.

Either the documentation should be updated that this doesn't work (or just not mention it),
or the code should be updated to support this.

**Comment by justinbmeyer** [comment]
Thanks for pointing this out.  This codepen verifies this doesn't work in CanJS 5: https://codepen.io/justinbmeyer/pen/ydxgWP?editors=1011

We need to update the docs.  I think they are a holdover from CanJS 3.  The `deparam` example uses 3.0.
